#!/bin/sh

# Docker registry password (use access token from Docker Hub)
export KAMAL_REGISTRY_PASSWORD="your-docker-hub-access-token"

# Rails master key from config/master.key
export RAILS_MASTER_KEY="$(cat config/master.key)"
